### ISSUE TITLE
Congratulations and Data Request for Han et al.'s Science Translational Medicine Study

### ISSUE THREAD

**Issue by OlafTobark42** [LabGenExp/Spatial_MCAO#3]
Hello Prof. Valihrach and Dr. Zucha,

Congratulations on your recent publication in PNAS! I also wanted to thank you for making the data and code openly available – it’s truly beneficial to the research community.

I am currently working on stroke-related spatial transcriptomics data, including datasets from Scott et al. (University of Toronto, Nature Communications), Han et al. (Southeast University, Science Translational Medicine), and Huiya Li et al. (Nanjing University’s Gulou Hospital, Genome Medicine). While Scott et al.’s data is openly accessible and manageable for analysis, the data from Huiya Li’s study has not yet been shared. For Han et al.'s Science Translational Medicine study, I was only able to locate the raw sequencing BAM files, and unfortunately, I have not found the image data necessary for importing into Seurat for reanalysis.

If possible, would you be able to share a Seurat object, h5 file, or any raw data format that includes image data compatible with reanalysis for Han et al.'s dataset? I would be immensely grateful for any assistance in this regard.

Thank you again, and congratulations on your excellent work!

Best regards,
Ziqi Cheng,
Wuhan University, China

**Comment by DanielZucha** [comment]
Dear @OlafTobark42 , 

Thank you for your kind congratulations. For the meantime, I was granted an explicit permission by Han et al. study authors to share the dataset with you. The dataset was shared through cesnet infrastructure to gulijuan@whu.edu.cn. In case of further enquiries, please let me know.

Best wishes, 
Daniel
